# Generated by Django 4.2.2 on 2023-07-02 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_orm_app', '0003_alter_author_table_alter_blog_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='updation_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
